#!/bin/sh
# Platform-specific shell configuration bootstrap.
# © 2013 Tom Vincent <http://tlvince.com/contact>

# As determined by profile
case "$PLATFORM" in
  "Darwin") source "$XDG_CONFIG_HOME/osx/shell.sh";;
    "Arch") source "$XDG_CONFIG_HOME/arch/shell.sh";;
esac
