#!/bin/sh
# Platform-specific shell configuration bootstrap.
# © 2013 Tom Vincent <http://tlvince.com/contact>

# As determined by profile
case "$PLATFORM" in
  "Darwin") source "$HOME/.osx/shell.sh";;
    "Arch") source "$HOME/.arch/shell.sh";;
esac
